services:
  backend:
    build:
      context: backend
    ports:
      - 8088:8080
    environment:
      - ASPNETCORE_URLS=http://+:8080

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src:rw
    ports:
      - "8080:5173"
    env_file:
      - ./frontend/.env