services:
  backend:
    build:
      context: backend
    ports:
      - 8088:8080
    environment:
      - ASPNETCORE_URLS=http://+:8080

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    env_file:
      - ./frontend/.env.production