FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY "service.csproj" .
RUN dotnet restore "service.csproj"
COPY . .
WORKDIR /src
RUN dotnet build "service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "service.dll"]

FROM node
WORKDIR /app
COPY package.json .
RUN npm install
COPY . . 
EXPOSE 8080
CMD [ "npm", "start" ]